#Opciones de simulacion
CC=gcc
#LDLIBS= -L. -lm5272_sim
#CFLIB_SIM_OBJS=m5272adc_dac_sim.o
COSAS=
#-----------------------
#Opciones de coldfire
#CC=m68k-elf-gcc
#LDLIBS= -L. -lm5272
#CFLIB_OBJS=
#-----------------------
CFLAGS=-g -Wall -Werror -I
#%.a:
# ar rcs $@ $^
#libm5272.a: $(CFLIB_OBJS)
#libm5272_sim.a: $(CFLIB_SIM_OBJS)
#visualizacionOsciloscopio.o interrupciones.o
OBJECTS = main.o ./lib/m5272adc_dac_sim.o ./lib/teclado_matricial_sim.o 
FUENTES = main.c ./lib/m5272adc_dac_sim.c ./lib/teclado_matricial_sim.c 


main: $(OBJECTS)
	$(CC) $(OBJECTS) $(CFLAGS) -o main

depend:
	makedepend $(FUENTES) 
# DO NOT DELETE

main.o: ./lib/m5272adc_dac_sim.h /usr/include/stdlib.h
main.o: /usr/include/Availability.h /usr/include/AvailabilityInternal.h
main.o: /usr/include/_types.h /usr/include/sys/_types.h
main.o: /usr/include/sys/cdefs.h /usr/include/sys/_symbol_aliasing.h
main.o: /usr/include/sys/_posix_availability.h /usr/include/machine/_types.h
main.o: /usr/include/i386/_types.h /usr/include/sys/wait.h
main.o: /usr/include/sys/_types/_pid_t.h /usr/include/sys/_types/_id_t.h
main.o: /usr/include/sys/signal.h /usr/include/sys/appleapiopts.h
main.o: /usr/include/machine/signal.h /usr/include/i386/signal.h
main.o: /usr/include/machine/_mcontext.h /usr/include/i386/_mcontext.h
main.o: /usr/include/mach/i386/_structs.h
main.o: /usr/include/sys/_types/_sigaltstack.h
main.o: /usr/include/sys/_types/_ucontext.h
main.o: /usr/include/sys/_types/_pthread_attr_t.h
main.o: /usr/include/sys/_types/_sigset_t.h /usr/include/sys/_types/_size_t.h
main.o: /usr/include/sys/_types/_uid_t.h /usr/include/sys/resource.h
main.o: /usr/include/stdint.h /usr/include/sys/_types/_int8_t.h
main.o: /usr/include/sys/_types/_int16_t.h /usr/include/sys/_types/_int32_t.h
main.o: /usr/include/sys/_types/_int64_t.h /usr/include/_types/_uint8_t.h
main.o: /usr/include/_types/_uint16_t.h /usr/include/_types/_uint32_t.h
main.o: /usr/include/_types/_uint64_t.h /usr/include/sys/_types/_intptr_t.h
main.o: /usr/include/sys/_types/_uintptr_t.h /usr/include/_types/_intmax_t.h
main.o: /usr/include/_types/_uintmax_t.h /usr/include/sys/_types/_timeval.h
main.o: /usr/include/machine/endian.h /usr/include/i386/endian.h
main.o: /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h
main.o: /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h
main.o: /usr/include/sys/_types/_ct_rune_t.h
main.o: /usr/include/sys/_types/_rune_t.h /usr/include/sys/_types/_wchar_t.h
main.o: /usr/include/sys/_types/_null.h /usr/include/machine/types.h
main.o: /usr/include/i386/types.h /usr/include/sys/_types/___offsetof.h
main.o: /usr/include/sys/_types/_dev_t.h /usr/include/sys/_types/_mode_t.h
main.o: /usr/include/errno.h /usr/include/sys/errno.h
main.o: /usr/include/sys/_types/_errno_t.h ./lib/teclado_matricial_sim.h
./lib/m5272adc_dac_sim.o: /usr/include/stdlib.h /usr/include/Availability.h
./lib/m5272adc_dac_sim.o: /usr/include/AvailabilityInternal.h
./lib/m5272adc_dac_sim.o: /usr/include/_types.h /usr/include/sys/_types.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/cdefs.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_symbol_aliasing.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_posix_availability.h
./lib/m5272adc_dac_sim.o: /usr/include/machine/_types.h
./lib/m5272adc_dac_sim.o: /usr/include/i386/_types.h /usr/include/sys/wait.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_pid_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_id_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/signal.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/appleapiopts.h
./lib/m5272adc_dac_sim.o: /usr/include/machine/signal.h
./lib/m5272adc_dac_sim.o: /usr/include/i386/signal.h
./lib/m5272adc_dac_sim.o: /usr/include/machine/_mcontext.h
./lib/m5272adc_dac_sim.o: /usr/include/i386/_mcontext.h
./lib/m5272adc_dac_sim.o: /usr/include/mach/i386/_structs.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_sigaltstack.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_ucontext.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_pthread_attr_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_sigset_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_size_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_uid_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/resource.h /usr/include/stdint.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_int8_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_int16_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_int32_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_int64_t.h
./lib/m5272adc_dac_sim.o: /usr/include/_types/_uint8_t.h
./lib/m5272adc_dac_sim.o: /usr/include/_types/_uint16_t.h
./lib/m5272adc_dac_sim.o: /usr/include/_types/_uint32_t.h
./lib/m5272adc_dac_sim.o: /usr/include/_types/_uint64_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_intptr_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_uintptr_t.h
./lib/m5272adc_dac_sim.o: /usr/include/_types/_intmax_t.h
./lib/m5272adc_dac_sim.o: /usr/include/_types/_uintmax_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_timeval.h
./lib/m5272adc_dac_sim.o: /usr/include/machine/endian.h
./lib/m5272adc_dac_sim.o: /usr/include/i386/endian.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_endian.h
./lib/m5272adc_dac_sim.o: /usr/include/libkern/_OSByteOrder.h
./lib/m5272adc_dac_sim.o: /usr/include/libkern/i386/_OSByteOrder.h
./lib/m5272adc_dac_sim.o: /usr/include/alloca.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_ct_rune_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_rune_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_wchar_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_null.h
./lib/m5272adc_dac_sim.o: /usr/include/machine/types.h
./lib/m5272adc_dac_sim.o: /usr/include/i386/types.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/___offsetof.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_dev_t.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_mode_t.h
./lib/m5272adc_dac_sim.o: /usr/include/errno.h /usr/include/sys/errno.h
./lib/m5272adc_dac_sim.o: /usr/include/sys/_types/_errno_t.h
