#!/usr/bin/expect --

set timeout 60
set send_human {.1 .3 1 .05 2}

set f [open [lindex $argv 0] r]
set data [read $f]
close $f

spawn ../utils/serial-console -d /dev/ttyS0 -s 19200 -m 8N1
send "\r"
expect "dBUG> "
send "dl\r"
expect "send S-records now...\r"

send "$data"
send "\r"
expect "dBUG> "
send "go 30000\r"
expect "dBUG> "
interact

